### ISSUE TITLE
Creating new users

### ISSUE THREAD

**Issue by albertosoho** [maotora/koa-userapi#1]
Hi,

I'm trying to create a new user:

`curl -H "Content-Type: application/json" http://localhost:3000/api/v1/users/create -X PUT -d '{"username": "john","password": "doe"}'
`

It returns "Accepted" but when I try to list all users it returns an empty array.

**Comment by maotora** [comment]
Hi @albertosoho ,

You are using PUT instead of POST.

The `create` route is expecting a POST request.
I took your code fired up the server changed the PUT to POST and it worked by giving me a jwt key that I can later use to search for a list of users.

**Comment by albertosoho** [comment]
Hi @maotora Thanks for your reply.

If i do that 

`curl -H "Content-Type: application/json" http://localhost:3001/api/v1/users/create -X POST -d '{"username": "john","password": "doe"}'`

It returns **Not Found**

**Comment by maotora** [comment]
I just checked again with same command (except the PORT part) and I get results.

Maybe post your repo so I can check. I can't reproduce this issue.

## EDIT

You can also try the `/signup` route.
I use it for my tests but it does the same functionality.

just do 
```bash
curl -H "Content-Type: application/json" http://localhost:3000/api/v1/signup -X POST -d '{"username": "john112","password": "doe"}'
```

**Comment by maotora** [comment]
@albertosoho did the solution fix your issue?

I will soon get back to this project and make some major changes and would like to know if it has unfixed bugs before moving on.
